import datetime
print(datetime.date.today())
date=datetime.datetime.now()
t=date.strftime("%H:%M:%S")
print(t)
x=date.strftime("%A")
print(x)
y=date.strftime("%Y")
print(y)
m=date.strftime("%m")
print(m)
ampm=date.strftime("%H:%M:%S:%p")
print(ampm)
localdate=date.strftime("%x")
print(localdate)
c=date.strftime("%c")
print(c)