a= 'welcome to Kannur'
b= "NICE TO MEET U"
print(a.isupper())
print(b.isupper())
print(a.split())
print(len(a))
print(a.capitalize())
print(a.upper())
print(a.count("e",0,8))
print(a.find("Ka"))
print(a.title())
print(a.replace("Kannur","Payyanur"))
print("hello \n hai")
print("hello \\n hai")
print(r"hello \n hai")
